<?php

namespace App;

use App\Abstracts\Organization;
use App\Traits\UuidTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Class MembershipLevel.
 *
 * @property string id
 * @property string organization_id
 * @property string organization_type
 * @property string name
 * @property string description
 * @property float dues
 * @property string dues_structure
 * @property string created_by
 * @property string updated_by
 * @property Carbon created_at
 * @property Carbon updated_at
 *
 * Relationships
 * @property \Illuminate\Database\Eloquent\Collection memberships
 * @property Organization organization
 * @property Character createdBy
 * @property Character lastUpdatedBy
 * @property \Illuminate\Database\Eloquent\Collection roles
 * @property \Illuminate\Database\Eloquent\Collection membershipFees
 * @property \Illuminate\Database\Eloquent\Collection discounts
 */
class MembershipLevel extends Model
{
    use UuidTrait;

    const DUES_STRUCTURE_PER_DAY = 'per_day';
    const DUES_STRUCTURE_PER_WEEK = 'per_week';
    const DUES_STRUCTURE_PER_MONTH = 'per_month';
    const DUES_STRUCTURE_PER_QUARTER = 'per_quarter';
    const DUES_STRUCTURE_PER_HALF = 'per_half';
    const DUES_STRUCTURE_PER_YEAR = 'per_year';
    const DUES_STRUCTURE_UPON_JOINING = 'upon_joining';
    const DUES_STRUCTURE_NEVER = 'never';

    const ALLOWED_DUE_STRUCTURES = [
        self::DUES_STRUCTURE_PER_DAY,
        self::DUES_STRUCTURE_PER_WEEK,
        self::DUES_STRUCTURE_PER_MONTH,
        self::DUES_STRUCTURE_PER_QUARTER,
        self::DUES_STRUCTURE_PER_HALF,
        self::DUES_STRUCTURE_PER_YEAR,
        self::DUES_STRUCTURE_UPON_JOINING,
        self::DUES_STRUCTURE_NEVER,
    ];

    const DEFAULT_DATA = [
        'name'           => 'Default',
        'description'    => 'Auto-Generated by Eve Commander',
        'dues_structure' => self::DUES_STRUCTURE_NEVER,
    ];

    /**
     * Get relation between this membership level and any memberships that belong to it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function memberships()
    {
        return $this->hasMany(Membership::class);
    }

    /**
     * Get relation between this membership level and the organization that owns it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function organization()
    {
        return $this->morphTo();
    }

    /**
     * Get relation between this membership level and the character that created it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function createdBy()
    {
        return $this->belongsTo(Character::class, 'created_by');
    }

    /**
     * Get relation between this membership level and the character that last updated it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lastUpdatedBy()
    {
        return $this->belongsTo(Character::class, 'last_updated_by');
    }

    /**
     * Get relation between this membership level and any roles that are assigned to it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class)->withTimestamps();
    }

    /**
     * Get relation between this membership level and any membership fees that are assigned to it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function membershipFees()
    {
        return $this->morphedByMany(MembershipFee::class, 'chargable')->withTimestamps();
    }

    /**
     * Get relation between this membership level and any membership fees that are assigned to it.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function discounts()
    {
        return $this->morphedByMany(Discount::class, 'chargable')->withTimestamps();
    }
}
